services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8083:8080"
    volumes:
      - nifi-data:/opt/nifi/nifi-current/conf 
    environment:
      - NIFI_WEB_HTTP_PORT=8080

volumes:
  nifi-data:
