services:
  mongo:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    container_name: mongodb
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    ports:
      - "${MONGODB_PORT:-27017}:27017"

volumes:
  mongodb_data:
    external: true
    name: ${MONGODB_DATA_DOCKER_VOLUME}
