services:
  clickhouse:
    image: 'clickhouse/clickhouse-server:${CLICKHOUSE_IMAGE_TAG:-latest}'
    container_name: clickhouse-server
    hostname: clickhouse
    restart: unless-stopped
    user: root
    env_file:
      - path: .env # default
        required: true
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./logs:/var/log/clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"

volumes:
  clickhouse_data: